In [2]:
import numpy as np

In [3]:
arr=np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

5

In [6]:
arr[5:8]

array([5, 6, 7])

In [7]:
arr[5:8]=12

In [8]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr_slice=arr[5:8]

In [10]:
arr_slice[1]=12345

In [11]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [12]:
arr_slice[:]=64

In [13]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [14]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
arr2d[2]

array([7, 8, 9])

In [16]:
arr2d[0][2]

3

In [17]:
arr2d[0,2]

3