In [1]:
import numpy as np

In [4]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [5]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
old_values=arr3d[0].copy()

In [8]:
arr3d[0]=42

In [9]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d[0]=old_values

In [11]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d[1,0]

array([7, 8, 9])

In [14]:
arr=np.arange(10)

In [15]:
arr[1:6]

array([1, 2, 3, 4, 5])